Feature/social follower following list page
DevelopLife/reviewtwits_frontend pull request #189
Opened 2023-05-02 11:31 UTC by ahn0min

## 📌 전반적인 개발 내용

- 해당 PR의 목적에 대해 간단히 설명해주세요.

<br>

## 💻 변경 내용

- 변경 내용에 대해 목록화 하여 설명해주세요.

<br>

## ✅ 관심 리뷰

- 어떤 부분에 대해 집중적으로 리뷰가 필요한지 설명해주세요.

2023-05-03 00:45 UTC, userJu commented on hooks/queries/sns.ts
> +  const data = linkageInfiniteScrollData(followerListQuery?.data);
제 로컬에서는 38번째 줄 followerListQuery?.data와 231번째 줄에 타입 에러가 발생합니다.
useInfiniteScrollQuery에서 반환된 data와 linkageInfiniteScrollData 함수에 제네릭으로 들어가는 타입이 불일치해서 발생하는 문제로 생각됩니다! 혹시 관련 부분 에러 확인해보셨을까요?

2023-05-03 00:45 UTC, userJu commented on hooks/queries/sns.ts
> +  const data = linkageInfiniteScrollData(followerListQuery?.data);
linkageInfiniteScrollData 타입을 확장하는 것보다 useInfiniteScrollQuery에서 반환되는 값을 좁혀야 할 것 같다는 생각이 드네요 한번 생각해보겠습니다!!🦾👏

2023-05-03 04:53 UTC, ahn0min commented on hooks/queries/sns.ts
> +  const data = linkageInfiniteScrollData(followerListQuery?.data);
네 생각해보시고 말씀해주세요 :)

2023-05-03 12:02 UTC, Jisu00 requested changes

2023-05-03 12:02 UTC, Jisu00 commented on api/sns.ts
파일 맨 아래의 `type FollowAndUnFollowRequestBody`에 대해서 따로 분리를 해주면 좋을 것 같습니다!

2023-05-03 13:46 UTC, userJu approved these changes

2023-05-03 13:46 UTC, userJu commented on hooks/queries/useInfiniteScrollQuery.tsx
> +}: UseInfiniteScrollQueryParams<T, K>): UseInfiniteQueryResult<T[], unknown> {
확인했습니다 반환타입을 확실하게 정해주니 타입 혼동이 없는 것 같아요! 👍👍

2023-05-11 09:36 UTC, Jisu00 approved these changes

2023-05-11 09:36 UTC, merged